version: "3"

name: tiktok-shop-recommender

services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - tiktok_shop_recommender_postgres_data:/var/lib/postgresql/data
      - ./postgres/vector_extension.sql:/docker-entrypoint-initdb.d/vector_extension.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api-node:
    build:
      context: ./api-node
      dockerfile: Dockerfile.dev
    volumes:
      - ./api-node:/app
      - ./api-node/bin:/app/bin
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    command: sh -c "make watch"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev


  recommendation:
      build:
        context: ./recommendation-node
        dockerfile: Dockerfile.dev
      ports:
        - "50051:50051"
      volumes:
        - ./recommendation-node:/app
      depends_on:
        postgres:
          condition: service_healthy
      environment:
        - PYTHONDONTWRITEBYTECODE=1
        - PYTHONUNBUFFERED=1
      command: sh -c "poetry run dev"

volumes:
  tiktok_shop_recommender_postgres_data: