version: "3"

name: tiktok-shop-recommender

services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - tiktok_shop_recommender_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vectorexample
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api-node:
    build:
      context: ./api-node
      dockerfile: Dockerfile.dev
    volumes:
      - ./api-node:/app
      - ./api-node/bin:/app/bin
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    command: sh -c "make watch"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev


  #recommendation-node:
  #  build:
  #    context: ./api-node
  #    dockerfile: Dockerfile.dev
  #  volumes:
  #    - ./recommendation-node:/app
  #  ports:
  #    - "8081:8081"
  #  depends_on:
  #    - postgres
  #    - api-node
  #  environment:
  #    - DB_HOST=postgres
  #    - DB_PORT=5432
  #    - DB_NAME=vectorexample
  #    - DB_USER=postgres
  #    - DB_PASSWORD=postgres

volumes:
  tiktok_shop_recommender_postgres_data:
