FROM python:3.9-slim

WORKDIR /app

RUN pip install --upgrade pip && \
    pip install poetry watchdog[watchmedo]

COPY pyproject.toml poetry.lock* ./
COPY recommendation ./recommendation
COPY protos ./protos

RUN poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi

COPY . .

# Generate proto files
RUN poetry run generate-proto

EXPOSE 50051

CMD ["poetry", "run", "start"]