# Start from the latest golang base image
FROM golang:latest

# Install make and PostgreSQL client
RUN apt-get update && apt-get install -y make postgresql-client protobuf-compiler


# Set the Current Working Directory inside the container
WORKDIR /app

RUN go install github.com/air-verse/air@latest && \
    go install google.golang.org/protobuf/cmd/protoc-gen-go@latest && \
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Expose port 8080 to the outside world
EXPOSE 8080

# Command to run the executable
CMD ["make", "watch"]
